sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t colleenberbon/multicontainer-docker-fibo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true colleenberbon/multicontainer-docker-fibo-test npm test

after_success:
  - docker build -t colleenberbon/multicontainer-fibo-client ./client
  - docker build -t colleenberbon/multicontainer-fibo-nginx ./nginx
  - docker build -t colleenberbon/multicontainer-fibo-server ./server
  - docker build -t colleenberbon/multicontainer-fibo-worker ./worker
  #Log in to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take these images to docker hub
  - docker push colleenberbon/multicontainer-fibo-client
  - docker push colleenberbon/multicontainer-fibo-nginx
  - docker push colleenberbon/multicontainer-fibo-server 
  - docker push colleenberbon/multicontainer-fibo-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multicontainer-fibo
  env: MulticontainerFibo-env
  bucket_name: elasticbeanstalk-us-east-2-265913181504
  bucket_path: multicontainer-fibo
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY